//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeckManagerOutput.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeckManagerOutput.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Button_Done {
            get {
                return ResourceManager.GetString("Button_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Centurion boards Galactica! \r\n.
        /// </summary>
        internal static string CenturionBoardsGalactica {
            get {
                return ResourceManager.GetString("CenturionBoardsGalactica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Centurion is destroyed! \r\n.
        /// </summary>
        internal static string CenturionDestroyed {
            get {
                return ResourceManager.GetString("CenturionDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centurions advance! \r\n.
        /// </summary>
        internal static string CenturionsAdvance {
            get {
                return ResourceManager.GetString("CenturionsAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {1} now in {2}! \r\n.
        /// </summary>
        internal static string ComponentMovement {
            get {
                return ResourceManager.GetString("ComponentMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order to replace Crises is the same on two or more Crises.  The replacement order must be unique..
        /// </summary>
        internal static string CrisisManagementForm_BadReplacementOrder {
            get {
                return ResourceManager.GetString("CrisisManagementForm_BadReplacementOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to set two or more Crises as the active Crisis.  Only one may be set as active..
        /// </summary>
        internal static string CrisisManagementForm_TooManyCrisesSetAsActive {
            get {
                return ResourceManager.GetString("CrisisManagementForm_TooManyCrisesSetAsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To avoid accidental crisis burying, please draw a crisis before attempting to bury it..
        /// </summary>
        internal static string GameWindow_buryTopToolStripMenuItem_SelectCrisisBeforeBury {
            get {
                return ResourceManager.GetString("GameWindow_buryTopToolStripMenuItem_SelectCrisisBeforeBury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a number greater than 0..
        /// </summary>
        internal static string GameWindow_drawMultipleToolStripMenuItem_InputMoreThanZero {
            get {
                return ResourceManager.GetString("GameWindow_drawMultipleToolStripMenuItem_InputMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Now!.
        /// </summary>
        internal static string GameWindow_JumpPrepChanged_JumpNow {
            get {
                return ResourceManager.GetString("GameWindow_JumpPrepChanged_JumpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jumping!.
        /// </summary>
        internal static string GameWindow_JumpPrepChanged_NoJumping {
            get {
                return ResourceManager.GetString("GameWindow_JumpPrepChanged_NoJumping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk 1!.
        /// </summary>
        internal static string GameWindow_JumpPrepChanged_Risk1 {
            get {
                return ResourceManager.GetString("GameWindow_JumpPrepChanged_Risk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk 3!.
        /// </summary>
        internal static string GameWindow_JumpPrepChanged_Risk3 {
            get {
                return ResourceManager.GetString("GameWindow_JumpPrepChanged_Risk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Games (*.bsg)|*.bsg.
        /// </summary>
        internal static string GameWindow_SavedGamesFilter {
            get {
                return ResourceManager.GetString("GameWindow_SavedGamesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Skill Cards.
        /// </summary>
        internal static string GameWindow_ShowHandMenuItemClick_HelpForm_Title {
            get {
                return ResourceManager.GetString("GameWindow_ShowHandMenuItemClick_HelpForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string GameWindowForm_MainMenu_Game {
            get {
                return ResourceManager.GetString("GameWindowForm_MainMenu_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load....
        /// </summary>
        internal static string GameWindowForm_MainMenu_Game_Load {
            get {
                return ResourceManager.GetString("GameWindowForm_MainMenu_Game_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string GameWindowForm_MainMenu_Game_New {
            get {
                return ResourceManager.GetString("GameWindowForm_MainMenu_Game_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        internal static string GameWindowForm_MainMenu_Game_Save {
            get {
                return ResourceManager.GetString("GameWindowForm_MainMenu_Game_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battlestar Galactica Game Manager.
        /// </summary>
        internal static string GameWindowForm_Text {
            get {
                return ResourceManager.GetString("GameWindowForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Jump.
        /// </summary>
        internal static string JumpPrep_AutoJump {
            get {
                return ResourceManager.GetString("JumpPrep_AutoJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump prep {0}! Now at {1}! \r\n.
        /// </summary>
        internal static string JumpPrep_Base {
            get {
                return ResourceManager.GetString("JumpPrep_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreases.
        /// </summary>
        internal static string JumpPrep_Decrease {
            get {
                return ResourceManager.GetString("JumpPrep_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases.
        /// </summary>
        internal static string JumpPrep_Increase {
            get {
                return ResourceManager.GetString("JumpPrep_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red 1.
        /// </summary>
        internal static string JumpPrep_Red1 {
            get {
                return ResourceManager.GetString("JumpPrep_Red1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red 2.
        /// </summary>
        internal static string JumpPrep_Red2 {
            get {
                return ResourceManager.GetString("JumpPrep_Red2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red 3.
        /// </summary>
        internal static string JumpPrep_Red3 {
            get {
                return ResourceManager.GetString("JumpPrep_Red3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk 1.
        /// </summary>
        internal static string JumpPrep_Risk1 {
            get {
                return ResourceManager.GetString("JumpPrep_Risk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk 3.
        /// </summary>
        internal static string JumpPrep_Risk3 {
            get {
                return ResourceManager.GetString("JumpPrep_Risk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked player not found in the current game state.  This should probably never happen!  PANIC..
        /// </summary>
        internal static string ManagePlayer_ClickedPlayerNotFound {
            get {
                return ResourceManager.GetString("ManagePlayer_ClickedPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some characters&apos; special abilities require extra loyalty cards to be dealt into the deck, such as Gaius Baltar or Sharon &quot;Boomer&quot; Valerii.  Or perhaps you&apos;re playing a house ruled variant of the game!  This option will give you extra \b&quot;You are NOT a Cylon&quot;\b0  cards in your starting Loyalty deck..
        /// </summary>
        internal static string OptionalRulesForm_ExtraLoyaltyCards_Text {
            get {
                return ResourceManager.GetString("OptionalRulesForm_ExtraLoyaltyCards_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Rules.
        /// </summary>
        internal static string OptionalRulesForm_FormName {
            get {
                return ResourceManager.GetString("OptionalRulesForm_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Loyalty Cards Needed:.
        /// </summary>
        internal static string OptionalRulesForm_OptionalRulesForm_ExtraLoyaltyCardsLabel_Text {
            get {
                return ResourceManager.GetString("OptionalRulesForm_OptionalRulesForm_ExtraLoyaltyCardsLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sympathizer:.
        /// </summary>
        internal static string OptionalRulesForm_OptionalRulesForm_SympathizerLabel_Text {
            get {
                return ResourceManager.GetString("OptionalRulesForm_OptionalRulesForm_SympathizerLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using this rule, an extra \b&quot;Sympathizer&quot;\b0  loyalty card will be dealt into the loyalty deck on game creation.  Rules surrounding this card are on page 19 of the Core Rulebook..
        /// </summary>
        internal static string OptionalRulesForm_Sympathizer_Text {
            get {
                return ResourceManager.GetString("OptionalRulesForm_Sympathizer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT Using Sympathizer.
        /// </summary>
        internal static string OptionalRulesForm_SympathizerCheckBoxCheckedChanged_Sympathizer_False {
            get {
                return ResourceManager.GetString("OptionalRulesForm_SympathizerCheckBoxCheckedChanged_Sympathizer_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Sympathizer.
        /// </summary>
        internal static string OptionalRulesForm_SympathizerCheckBoxCheckedChanged_Sympathizer_True {
            get {
                return ResourceManager.GetString("OptionalRulesForm_SympathizerCheckBoxCheckedChanged_Sympathizer_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        internal static string PlayerRosterForm_AddPlayerButton_Text {
            get {
                return ResourceManager.GetString("PlayerRosterForm_AddPlayerButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player is attempting to draw too many {0} cards.  Please check their initial draw against their valid draws..
        /// </summary>
        internal static string PlayerRosterForm_AddPlayerButtonClick_InvalidColors {
            get {
                return ResourceManager.GetString("PlayerRosterForm_AddPlayerButtonClick_InvalidColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial 3-card draw is required..
        /// </summary>
        internal static string PlayerRosterForm_AddPlayerButtonClick_NoDrawSelected {
            get {
                return ResourceManager.GetString("PlayerRosterForm_AddPlayerButtonClick_NoDrawSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player must have a unique name..
        /// </summary>
        internal static string PlayerRosterForm_AddPlayerButtonClick_NoPlayerName {
            get {
                return ResourceManager.GetString("PlayerRosterForm_AddPlayerButtonClick_NoPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Details.
        /// </summary>
        internal static string PlayerRosterForm_CharacterDetailButton_Text {
            get {
                return ResourceManager.GetString("PlayerRosterForm_CharacterDetailButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Character selected, or no Characters loaded.  Select a Character to get details..
        /// </summary>
        internal static string PlayerRosterForm_CharacterDetailButtonClick_No_Character_selected {
            get {
                return ResourceManager.GetString("PlayerRosterForm_CharacterDetailButtonClick_No_Character_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character:.
        /// </summary>
        internal static string PlayerRosterForm_CharacterListBoxLabel_Text {
            get {
                return ResourceManager.GetString("PlayerRosterForm_CharacterListBoxLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Roster.
        /// </summary>
        internal static string PlayerRosterForm_FormName {
            get {
                return ResourceManager.GetString("PlayerRosterForm_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Draw.
        /// </summary>
        internal static string PlayerRosterForm_InitialDrawGroupBox_Text {
            get {
                return ResourceManager.GetString("PlayerRosterForm_InitialDrawGroupBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name:.
        /// </summary>
        internal static string PlayerRosterForm_PlayerName_Text {
            get {
                return ResourceManager.GetString("PlayerRosterForm_PlayerName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Resource_Distance {
            get {
                return ResourceManager.GetString("Resource_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string Resource_Food {
            get {
                return ResourceManager.GetString("Resource_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        internal static string Resource_Fuel {
            get {
                return ResourceManager.GetString("Resource_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morale.
        /// </summary>
        internal static string Resource_Morale {
            get {
                return ResourceManager.GetString("Resource_Morale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population.
        /// </summary>
        internal static string Resource_Population {
            get {
                return ResourceManager.GetString("Resource_Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now at {1}!.
        /// </summary>
        internal static string ResourceChanged {
            get {
                return ResourceManager.GetString("ResourceChanged", resourceCulture);
            }
        }
    }
}
